[project]
name = "hexlet-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "piropatron", email = "piropatron1@yandex.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "dj-database-url>=3.1.2",
    "django>=6.1",
    "django-bootstrap5>=26.2",
    "django-filter>=26.1",
    "gunicorn>=26.0.0",
    "psycopg2>=2.9.12",
    "python-dotenv>=1.2.2",
    "sentry-sdk>=2.68.0",
]
[dependency-groups]
dev = [
    "django-extensions>=4.1",
    "ipython>=9.15.0",
    "pytest-django>=4.12.0",
    "ruff>=0.15.20",
]

[project.scripts]
task_manager = "task_manager:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
norecursedirs = "__pycache__"
addopts = "--strict-markers"
python_files = "tests.py"
DJANGO_SETTINGS_MODULE = "task_manager.settings"

