# Generated by Django 6.1 on 2026-08-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_alter_status_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
    ]
